# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3efd20fa3f534507bf97d8ab9f94b409b76fd41b2064b2f6b065e5dd542891bcf25635011c93988d72bcbf6a5758c1cf4ae30f0a6bd05262119ee4af1693e079

test:
  secret_key_base: ed2ca6c9a6b8cecaa26d669434f54cf26b2245206eeff97f2a1ab07209ac582afcb02d8ffb9625741aaaa9eb14f79bf88dfe53efbdf41439a3e4abee5a9c749c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
